// Generated by gencpp from file uwb_localization_description/position_data_uwb.msg
// DO NOT EDIT!


#ifndef UWB_LOCALIZATION_DESCRIPTION_MESSAGE_POSITION_DATA_UWB_H
#define UWB_LOCALIZATION_DESCRIPTION_MESSAGE_POSITION_DATA_UWB_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace uwb_localization_description
{
template <class ContainerAllocator>
struct position_data_uwb_
{
  typedef position_data_uwb_<ContainerAllocator> Type;

  position_data_uwb_()
    : destination_id()
    , distance()
    , stamp()
    , uwb_position()  {
    }
  position_data_uwb_(const ContainerAllocator& _alloc)
    : destination_id(_alloc)
    , distance(_alloc)
    , stamp(_alloc)
    , uwb_position(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<int64_t, typename ContainerAllocator::template rebind<int64_t>::other >  _destination_id_type;
  _destination_id_type destination_id;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _distance_type;
  _distance_type distance;

   typedef std::vector<ros::Time, typename ContainerAllocator::template rebind<ros::Time>::other >  _stamp_type;
  _stamp_type stamp;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _uwb_position_type;
  _uwb_position_type uwb_position;





  typedef boost::shared_ptr< ::uwb_localization_description::position_data_uwb_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::uwb_localization_description::position_data_uwb_<ContainerAllocator> const> ConstPtr;

}; // struct position_data_uwb_

typedef ::uwb_localization_description::position_data_uwb_<std::allocator<void> > position_data_uwb;

typedef boost::shared_ptr< ::uwb_localization_description::position_data_uwb > position_data_uwbPtr;
typedef boost::shared_ptr< ::uwb_localization_description::position_data_uwb const> position_data_uwbConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::uwb_localization_description::position_data_uwb_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::uwb_localization_description::position_data_uwb_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::uwb_localization_description::position_data_uwb_<ContainerAllocator1> & lhs, const ::uwb_localization_description::position_data_uwb_<ContainerAllocator2> & rhs)
{
  return lhs.destination_id == rhs.destination_id &&
    lhs.distance == rhs.distance &&
    lhs.stamp == rhs.stamp &&
    lhs.uwb_position == rhs.uwb_position;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::uwb_localization_description::position_data_uwb_<ContainerAllocator1> & lhs, const ::uwb_localization_description::position_data_uwb_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace uwb_localization_description

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::uwb_localization_description::position_data_uwb_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::uwb_localization_description::position_data_uwb_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::uwb_localization_description::position_data_uwb_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::uwb_localization_description::position_data_uwb_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uwb_localization_description::position_data_uwb_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uwb_localization_description::position_data_uwb_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::uwb_localization_description::position_data_uwb_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cffdb089f0ead7804716b039674b3438";
  }

  static const char* value(const ::uwb_localization_description::position_data_uwb_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcffdb089f0ead780ULL;
  static const uint64_t static_value2 = 0x4716b039674b3438ULL;
};

template<class ContainerAllocator>
struct DataType< ::uwb_localization_description::position_data_uwb_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uwb_localization_description/position_data_uwb";
  }

  static const char* value(const ::uwb_localization_description::position_data_uwb_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::uwb_localization_description::position_data_uwb_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64[] destination_id\n"
"float64[] distance\n"
"time[] stamp\n"
"float64[] uwb_position\n"
;
  }

  static const char* value(const ::uwb_localization_description::position_data_uwb_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::uwb_localization_description::position_data_uwb_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.destination_id);
      stream.next(m.distance);
      stream.next(m.stamp);
      stream.next(m.uwb_position);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct position_data_uwb_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::uwb_localization_description::position_data_uwb_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::uwb_localization_description::position_data_uwb_<ContainerAllocator>& v)
  {
    s << indent << "destination_id[]" << std::endl;
    for (size_t i = 0; i < v.destination_id.size(); ++i)
    {
      s << indent << "  destination_id[" << i << "]: ";
      Printer<int64_t>::stream(s, indent + "  ", v.destination_id[i]);
    }
    s << indent << "distance[]" << std::endl;
    for (size_t i = 0; i < v.distance.size(); ++i)
    {
      s << indent << "  distance[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.distance[i]);
    }
    s << indent << "stamp[]" << std::endl;
    for (size_t i = 0; i < v.stamp.size(); ++i)
    {
      s << indent << "  stamp[" << i << "]: ";
      Printer<ros::Time>::stream(s, indent + "  ", v.stamp[i]);
    }
    s << indent << "uwb_position[]" << std::endl;
    for (size_t i = 0; i < v.uwb_position.size(); ++i)
    {
      s << indent << "  uwb_position[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.uwb_position[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // UWB_LOCALIZATION_DESCRIPTION_MESSAGE_POSITION_DATA_UWB_H
